# docker-compose.yaml define and configure the "network of services"
services:
    # web server: nginx
    web:
        image: nginx:latest
        ports:
            - "80:80" # first is the local machine, second is port from container
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    # php
    app:
        build:
            dockerfile: Dockerfile
        volumes:
            -  ./:/app